package com.task.JDBC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
// import java.sql.JDBCHelper;

import java.util.Date;

public class TestJdbc {

    public static void main(String[] args) {

        System.out.println("Hello world!");
        Connection con = null;
        String url = "jdbc:hsqldb:hsql://localhost/xdb";
        String uid = "SA";
        String pass = "";

        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            con = DriverManager.getConnection(url, uid, pass);

            con.setAutoCommit(false); // transactions -> changes are not made permanent until I say so
            Statement stmt = con.createStatement();

            // testTestQuery(con);
            

        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        } finally {

        }
    }

    public static void testTestQuery(Connection con) {

        try {

            String sql1 = "insert into TESTTABLE(name,dop) values(?,?);";
            PreparedStatement ps1 = con.prepareStatement(sql1);
            String sql2 = "select * from TESTTABLE where name=?";
            PreparedStatement ps2 = con.prepareStatement(sql2);

            java.sql.Date sqlDate = new java.sql.Date(new Date().getTime());
            ps1.setString(1, "my string testing");
            ps1.setDate(2, sqlDate);
            ps1.execute();

            ps2.setString(1, "my string testing");
            ps2.execute();

            con.commit();

            ResultSet rs1 = ps1.getResultSet();
            ResultSet rs2 = ps2.getResultSet();
            while (rs2.next()) {
                String c1 = rs2.getString("name");
                java.sql.Date dat = rs2.getDate(2);

                System.out.println(c1 + dat);
            }

            // release the resources
            // JDBCHelper.close(ps1);
            // JDBCHelper.close(ps2);
            // JDBCHelper.close(rs1);
            // JDBCHelper.close(rs2);
            // JDBCHelper.close(con);

        } catch (SQLException e) {
            try {
                con.rollback();
            } catch (Exception ex) {
                System.out.println("unable to roll back");
            }

            e.printStackTrace();
        }
    }

    public static void testUserCreation(Connection con) {
        String sql1 = "create table cvusers(sl_no integer generated by default as identity primary key, name varchar(200) not null, email varchar(200) unique, phone char(15));";
        String sql2 = "create table cvaddr(sl_no integer generated by default as identity primary key, cvusers_sl integer references cvusers(sl_no), hnum varchar(20), city varchar(200));";
    }

    public static void testUserInsert(Connection con) {

    }
}
